#! /bin/bash
sed s/','/" ; "/g storms_109to129.txt | sed 's/$/ ; * ; y/g' > add_text.txt ; echo ' ' >> add_text.txt
sed s/','/" ; "/g storms_130to159.txt | sed 's/$/ ; * ; m/g' >> add_text.txt ; echo ' ' >> add_text.txt
sed s/','/" ; "/g storms_160to189.txt | sed 's/$/ ; * ; r/g' >> add_text.txt ; echo ' ' >> add_text.txt
sed s/','/" ; "/g storms_190to219.txt | sed 's/$/ ; * ; g/g' >> add_text.txt ; echo ' ' >> add_text.txt
sed s/','/" ; "/g storms_220to249.txt | sed 's/$/ ; * ; b/g' >> add_text.txt ; echo ' ' >> add_text.txt
sed s/','/" ; "/g storms_250to274.txt | sed 's/$/ ; * ; k/g' >> add_text.txt
